// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: max.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Max {
  public static partial class MaxService
  {
    static readonly string __ServiceName = "max.MaxService";

    static readonly grpc::Marshaller<global::Max.MaxRequest> __Marshaller_max_MaxRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Max.MaxRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Max.MaxResponse> __Marshaller_max_MaxResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Max.MaxResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Max.MaxRequest, global::Max.MaxResponse> __Method_Max = new grpc::Method<global::Max.MaxRequest, global::Max.MaxResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "Max",
        __Marshaller_max_MaxRequest,
        __Marshaller_max_MaxResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Max.MaxReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of MaxService</summary>
    [grpc::BindServiceMethod(typeof(MaxService), "BindService")]
    public abstract partial class MaxServiceBase
    {
      public virtual global::System.Threading.Tasks.Task Max(grpc::IAsyncStreamReader<global::Max.MaxRequest> requestStream, grpc::IServerStreamWriter<global::Max.MaxResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for MaxService</summary>
    public partial class MaxServiceClient : grpc::ClientBase<MaxServiceClient>
    {
      /// <summary>Creates a new client for MaxService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public MaxServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for MaxService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public MaxServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected MaxServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected MaxServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::Max.MaxRequest, global::Max.MaxResponse> Max(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Max(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Max.MaxRequest, global::Max.MaxResponse> Max(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_Max, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override MaxServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new MaxServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(MaxServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Max, serviceImpl.Max).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, MaxServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Max, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Max.MaxRequest, global::Max.MaxResponse>(serviceImpl.Max));
    }

  }
}
#endregion
