// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PrimeNumber.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace PrimeNumbers {
  public static partial class PrimeNumbersService
  {
    static readonly string __ServiceName = "primeNumbers.PrimeNumbersService";

    static readonly grpc::Marshaller<global::PrimeNumbers.PrimeRequest> __Marshaller_primeNumbers_PrimeRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::PrimeNumbers.PrimeRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::PrimeNumbers.PrimeResponse> __Marshaller_primeNumbers_PrimeResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::PrimeNumbers.PrimeResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::PrimeNumbers.PrimeRequest, global::PrimeNumbers.PrimeResponse> __Method_ListPrimeNumbers = new grpc::Method<global::PrimeNumbers.PrimeRequest, global::PrimeNumbers.PrimeResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "ListPrimeNumbers",
        __Marshaller_primeNumbers_PrimeRequest,
        __Marshaller_primeNumbers_PrimeResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::PrimeNumbers.PrimeNumberReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of PrimeNumbersService</summary>
    [grpc::BindServiceMethod(typeof(PrimeNumbersService), "BindService")]
    public abstract partial class PrimeNumbersServiceBase
    {
      public virtual global::System.Threading.Tasks.Task ListPrimeNumbers(global::PrimeNumbers.PrimeRequest request, grpc::IServerStreamWriter<global::PrimeNumbers.PrimeResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for PrimeNumbersService</summary>
    public partial class PrimeNumbersServiceClient : grpc::ClientBase<PrimeNumbersServiceClient>
    {
      /// <summary>Creates a new client for PrimeNumbersService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PrimeNumbersServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for PrimeNumbersService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PrimeNumbersServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PrimeNumbersServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PrimeNumbersServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::PrimeNumbers.PrimeResponse> ListPrimeNumbers(global::PrimeNumbers.PrimeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListPrimeNumbers(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::PrimeNumbers.PrimeResponse> ListPrimeNumbers(global::PrimeNumbers.PrimeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_ListPrimeNumbers, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PrimeNumbersServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PrimeNumbersServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PrimeNumbersServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ListPrimeNumbers, serviceImpl.ListPrimeNumbers).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PrimeNumbersServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ListPrimeNumbers, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::PrimeNumbers.PrimeRequest, global::PrimeNumbers.PrimeResponse>(serviceImpl.ListPrimeNumbers));
    }

  }
}
#endregion
